import streamlit as st
st.text("Hello!!")
st.title("I'm Takkola sowjanya!")
st.subheader("I'have completed my B.Tech in Ece from Narayana Engineering college, Nellore, Andhra Pradesh, India.")
st.write("I have a strong foundation in electronics and communication engineering, and I am passionate about applying my knowledge to real-world problems. I am eager to contribute my skills and enthusiasm to a dynamic team and continue learning and growing in the field of technology.")
st.title("My Skills")
st.write("Python")
st.image("https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80")
st.button("Download Resume" ,type="primary")
st.title("Wants to know more about me?")
st.write("You can reach me through my email:takkolaswojanya2005@gmail.com")
st.text("Ask Anything about me!! I will try to answer you as soon as possible.")
st.button("Click here to ask me a question?", type="primary"   )
